//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSVehicle
    {
        public long Id { get; set; }
        public int CategoryId { get; set; }
        public int BrandId { get; set; }
        public string VehicleName { get; set; }
        public string ModelName { get; set; }
        public string ModelYear { get; set; }
        public string Color { get; set; }
        public int Seats { get; set; }
        public double Price { get; set; }
        public double RentPerHour { get; set; }
        public string VehicleImage { get; set; }
        public bool Availability { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
    
        public virtual MSBrand MSBrand { get; set; }
        public virtual MSCategory MSCategory { get; set; }
    }
}
